version: "3"

services:
  db:
    image: postgres
    container_name: LABS_DB
    restart: unless-stopped
    environment:
      - POSTGRES_DB=PumaLab
      - POSTGRES_USER=lab_report
      - POSTGRES_PASSWORD=lab_report
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5400:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: puma_lab_app:latest
    restart: unless-stopped
    container_name: LABS_APP
    ports:
      - "8088:8088"
    volumes:
      - ./pumalabs:/pumalabs

    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8088"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=PumaLab
      - DB_USER=lab_report
      - DB_PASS=lab_report
      - DB_PORT=5432
volumes:
  db_data:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24