# Generated by Django 4.2 on 2024-07-25 14:19

import commercial.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("En traitement", "En traitement"),
                            ("Traité", "Traité"),
                            ("Clôturé", "Clôturé"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                ("distributeur_id", models.IntegerField()),
                ("distributeur", models.CharField(max_length=255)),
                ("client_id", models.IntegerField()),
                ("client", models.CharField(max_length=255)),
                ("project", models.CharField(max_length=500)),
                ("n_bc", models.CharField(max_length=25)),
                ("n_lot", models.CharField(max_length=25)),
                (
                    "qte",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_delivery", models.DateField()),
                ("date_prod", models.DateField()),
                ("observation", models.TextField(blank=True, null=True)),
                ("treatment_labo", models.TextField(blank=True, null=True)),
                ("treatment_site", models.TextField(blank=True, null=True)),
                ("actions", models.TextField(blank=True, null=True)),
                ("decision", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("designation", models.CharField(max_length=100)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Ouest", "Ouest"),
                            ("Est", "Est"),
                            ("Centre", "Centre"),
                            ("Centre/Ouest", "Centre/Ouest"),
                        ],
                        default="Ouest",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=commercial.models.get_image_filename,
                        verbose_name="Image",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.complaint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("En traitement", "En traitement"),
                            ("Traité", "Traité"),
                            ("Clôturé", "Clôturé"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("En traitement", "En traitement"),
                            ("Traité", "Traité"),
                            ("Clôturé", "Clôturé"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.complaint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="emplacement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commercial.emplacement"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commercial.product"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="usine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.usine"
            ),
        ),
    ]
