# Generated by Django 4.2 on 2024-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=250)),
            ],
        ),
    ]
